### ISSUE TITLE
Weight initialization might be superfluous

### ISSUE THREAD

**Issue by nasimrahaman** [locuslab/TCN#1]
It appears that the way `weight_norm` works in Pytorch makes [this line](https://github.com/nasimrahaman/tcn/blob/master/TCN/tcn.py#L37) in `TCN/tcn.py` superfluous, because [this line](https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/weight_norm.py#L46) registers a forward prehook that overwrites `module.weight` every forward pass. (FYI)

**Comment by jerrybai1995** [comment]
Yes, indeed, L34 is not effective here. Thanks for pointing this out :-)
