### ISSUE TITLE
Is the code for Residual Blocks provided?

### ISSUE THREAD

**Issue by chaitjo** [locuslab/TCN#10]
I was wondering if the repository in its current state has code to build the residual blocks shown in the paper (Figure 1 (b)). 

I'm trying to use your paper's insights to build CNN architectures for sequence modelling using keras and was a bit confused about implementing the shown residual block of 2 conv layers followed by a residual connection.

**Comment by jerrybai1995** [comment]
Yes, see https://github.com/locuslab/TCN/blob/master/TCN/tcn.py#L15 for the residual block class.

**Comment by chaitjo** [comment]
Thank you for the reply and the super useful paper. Additionally:

- What's the reasoning behind picking the number of conv layers inside a residual block as 2? 

- Can we also connect 'downstream' residual block inputs to 'upstream'/other residual block outputs too, instead of just the connection within the block itself?

(As someone completely unfamiliar with this technique from comouter vision, I'd greatly appreciate more insights on designing TCNs)
