### ISSUE TITLE
what if the input sequence length is not the same?

### ISSUE THREAD

**Issue by zhly0** [locuslab/TCN#11]
Hi,thanks for your code,this is not a issue,but my confusion,sorry to put it here:
    I want to use TCN for speech recognition,and I have some speech labeled with words,but these speech,they do not have the same length,like speech 1 duration is 10 second,speech 2 is 5 second,how can I use TCN for speech recognition?how can I handle the uncertainty of the input?
    Thanks,looking forward for your reply.

**Comment by jerrybai1995** [comment]
You can pad them to the same length. My suggestion would be that group inputs of similar lengths together and pad them to the length of the longest input in the group.

**Comment by zhly0** [comment]
Thanks，nice idea，I will try！
