### ISSUE TITLE
Why conv1d of pytorch is guranteed to be causal?

### ISSUE THREAD

**Issue by QiXuanWang** [locuslab/TCN#12]
In your paper, you mentioned that TCN should be causal and in Figure 1 it seems the conv is causal indeed.
But in this implementation, I see the only tweek is chomp1D and you used conv1d directly? 
Can we say that pytorch's conv1d is causual?

**Comment by huanglianghua** [comment]
@QiXuanWang The "causal" is simply achieved by shifting the output of ordinary `conv1d` by `(k-1)/2`, where `k` is the kernel size.

**Comment by QiXuanWang** [comment]
@huanglianghua Thanks for the comment. Where does `(k-1)/2`  come from?  And why is 'dilation'  missed in it?  Is it's chomp1d, then shouldn't shifting be "(k-1)*dilation"?

**Comment by jerrybai1995** [comment]
The `Chomp1D` class is to ensure causality. For more details, see #8.

**Comment by QiXuanWang** [comment]
@jerrybai1995 Thanks. That's confirmed my guess. I saw pytorch used C(i-1) for convolution of C(i) which somehow makes me think it's causal but indeed it should be Chomp1D.
