### ISSUE TITLE
Where are the poly_music datasets located?

### ISSUE THREAD

**Issue by leomrocha** [locuslab/TCN#13]
I haven't managed to find the datasets referenced in the utils inside the poly_music example.
With the observations package there is a jsb_chorales only dataset, but it is not pre-processed to be used by this algorithm, I have tried to adapt it but without success. Can you provide the link to download the pre-processed data .mat files?

**Comment by jerrybai1995** [comment]
It's in the repo: https://github.com/locuslab/TCN/tree/master/TCN/poly_music/mdata
