### ISSUE TITLE
some questions about word-level LM

### ISSUE THREAD

**Issue by JWChen123** [locuslab/TCN#15]
if i have many articles , they have different words. these articles maybe have some relationships. How can i integrate them?

**Comment by jerrybai1995** [comment]
You can still train them together, it's just that the vocabulary size will be large. See the LAMBADA task folder for an example. Basically, you can first make a pass through the articles to collect the corpus vocabulary, and then train the LM on that. I would also suggest you replacing the very-low frequency words with some token, such as <unk>.

**Comment by JWChen123** [comment]
Very thanks to your reply, in fact, my research is that users’ trajectory prediction. I use every user’s location record as trajectory. But every user has different number of record. Maybe user1 has 1000 records, user2 has 500 records.  I am studying a paper about RNN on this dataset. He split every user’s trajectory into a short piece of trajectory. He use all users’ short trajectory to train. Just like the seq2seq with input-output pairs dataset in machine translation. Can I use this dataset with your model?

**Comment by jerrybai1995** [comment]
Yes, I think temporal convolutions can handle cases like this. Note that since sequences have different lengths, you should be careful about the grouping (of sequences with similar lengths) and the truncation when applying TCN.
