### ISSUE TITLE
default for cuda in word_cnn is True, but code expects it to be False

### ISSUE THREAD

**Issue by lzamparo** [locuslab/TCN#16]
Lines 20-22 make the `cuda` arg `True` by default:
```
 parser.add_argument('--cuda', action='store_false',
                    help='use CUDA (default: True)')
```
Yet lines 60-62 test as if it expects `args.cuda` to be `False` by default:
```
if torch.cuda.is_available():
    if not args.cuda:
        print("WARNING: You have a CUDA device, so you should probably run with --cuda")
```
Maybe you could swap in the following for the argparser `--cuda` argument: 

```
parser.add_argument('--cuda', action='store_false', default=False,
                    help='use CUDA (default: True)')
```

For people wanting to test drive the code on small machines (i.e my laptop) it helps remove one snag.  I can do a quick PR if you like.  Thanks for sharing the code for these experiments, they are super useful!

**Comment by jerrybai1995** [comment]
Thanks for the suggestion! I will fix this in the next update :-)

**Comment by ECE-Engineer** [comment]
@jerrybai1995 I've was wondering if you had any recommendations for how one would go about combining this TCN architecture with an LSTM?

Thank you very much for your time.
