### ISSUE TITLE
Causal Transposed Convolution

### ISSUE THREAD

**Issue by ahmed-fau** [locuslab/TCN#19]
Hi,

Thanks for this great paper ... I am trying to use this architecture in auto-encoder setting such that the encoder part is a stack of strided-dilated-causal conv layers and now thinking about the decoder part.

In terms of up-sampling using transposed convolutions, does it follow the same intuition in order to have causal up-sampling (i.e. to exclude the reconstructions of future part) ? Or shall we generate sample-by-sample without transposed conv layers ?

With many thanks in advance
Best Regards

**Comment by fengyuxie** [comment]
Hi,
I am a student. When I run your code, I have a question to think about. Your MNIST pixel task is very good. The data set is very formal. When I have a self-data set, what changes should I make on your basis and how to do them?
Best Regards

**Comment by fengyuxie** [comment]
there is a error :RuntimeError: shape '[-1, 3, 16725]' is invalid for input of size 2408448.
I changed the input_channel=3 seq_length = int(50176/ input_channels)  50176=224*224   n_classes = 22

**Comment by david-waterworth** [comment]
@fengyuxie you should open a separate issue rather than adding an unrelated question to someone else's on guithub.

**Comment by MichelleYang2017** [comment]
> Hi,
> 
> Thanks for this great paper ... I am trying to use this architecture in auto-encoder setting such that the encoder part is a stack of strided-dilated-causal conv layers and now thinking about the decoder part.
> 
> In terms of up-sampling using transposed convolutions, does it follow the same intuition in order to have causal up-sampling (i.e. to exclude the reconstructions of future part) ? Or shall we generate sample-by-sample without transposed conv layers ?
> 
> With many thanks in advance
> Best Regards

Did you solve it? I am considering how to implement. I wonder how you did it ? Many thanks in advance!
