### ISSUE TITLE
Weight initialization method

### ISSUE THREAD

**Issue by PeikeLi** [locuslab/TCN#20]
I notice that in your code, you init all the weight like below. Is there any special reason for doing such way? why not init with xavier or other method?
`    def init_weights(self):
        self.conv1.weight.data.normal_(0, 0.01)
        self.conv2.weight.data.normal_(0, 0.01)
        if self.downsample is not None:
            self.downsample.weight.data.normal_(0, 0.01)
`

**Comment by jerrybai1995** [comment]
Thank you for your interest in our work!

No, there isn't any particular reason. We just used N(0, 0.01) for convenience. It is likely that other initialization scheme could work better.
