### ISSUE TITLE
Residual block:  1x1 convolution implementation

### ISSUE THREAD

**Issue by oshyshkin** [locuslab/TCN#21]
Hi! I'm learning your TCN architecture and I got stuck with an understanding of the next part.
In the code:
https://github.com/locuslab/TCN/blob/master/TCN/tcn.py#L30-L31

You sequentially add conv layer and chomp1d layer. I see that chomp1d cuts the last `padding` elements (which are redundant as I understand).

I assume that chomp1d == 1x1 conv described in the paper. But the code doesn't look like the same thing described the paper because:

1. In TemporalBlock it adds chomp1d after each conv layer. 
2. In the paper, it sums outputs when in the code it just cuts tensor.

My question is: 1x1 convolution from Fig 1.b == chomp1d? If yes then why it's different from the scheme in the paper and does it conceptually affect somehow? If not did you implement it somewhere or it's a good chance to try?)

I didn't work with NN a lot so I don't know some common thing and try to figure it out.

Thank you in advance!
Oleh

**Comment by jerrybai1995** [comment]
See #8 and #12 regarding this issue. `Chomp1d` does **not** perform convolution, and is different from a convolution. It is just there to ensure there is no leakage of information from future to the present. 

On a sequence x_{1:T}, if you simply perform (for instance) a kernel-2 convolution, you risk connecting x_t to y_{t-1}, which is forbidden. So what we do instead, is to add a left padding to the input.

**Comment by oshyshkin** [comment]
Okay, I found it:
https://github.com/locuslab/TCN/blob/master/TCN/tcn.py#L45

Sorry for bothering you!
