### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by swilson314** [locuslab/TCN#22]
I'm sorry for asking what I expect has a really obvious answer. I downloaded the zip file and I get the following results when I try add_test.py

(base) F:\PersystCode\Python\TCN-master\TCN\adding_problem>python add_test.py
Traceback (most recent call last):
File "add_test.py", line 5, in 
from TCN.adding_problem.model import TCN
ModuleNotFoundError: No module named 'TCN'

Clearly I need to install the TCN module. I tried >python tcn.py install, but that didn't seem to do anything.

**Comment by swilson314** [comment]
Copying the TCN folder to C:\Users\scott\Anaconda3\Lib\site-packages did the trick ;)

**Comment by jerrybai1995** [comment]
You can also just `import sys` and append the full path of the `TCN` folder by `sys.path.append` in the `add_test.py`. But I'm glad that you've solved it!

**Comment by swilson314** [comment]
Thanks!
