### ISSUE TITLE
invalid index of a 0-dim tensor

### ISSUE THREAD

**Issue by JurijsNazarovs** [locuslab/TCN#23]
Hello,

When I am running pmisst_test.py, I get following error: 

(Pdb) train_loss.data[0]
*** IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

It happens on line 98.

**Comment by jerrybai1995** [comment]
Yes, this code was implemented in PyTorch 0.3.0, and should work for 0.4.0 as well. If you are running on 1.0.0, please use `.item()` instead of `data[0]`.

We will update the repo soon so that it is PyTorch 1.0.0 compatible.

Thanks for pointing this out!
