### ISSUE TITLE
confused about mnist_pixel task

### ISSUE THREAD

**Issue by viviov** [locuslab/TCN#24]
Thanks for sharing, I'm confused about tcn model for mnist_pixel. In mnist model,  why just y1[:, :, -1] is ok? before linear layer.  why discard others?

**Comment by jerrybai1995** [comment]
You can certainly include the others (for instance, take the last 5 outputs and flatten them to a vector). Since y1[:, :, -1] has a receptive field that covers all the input pixels in the sequence, we think it is sufficient to just use this last output (which is what RNNs do on this task).

**Comment by viviov** [comment]
Thanks for your reply, I read your paper again, maybe I got it😄
