### ISSUE TITLE
Is tcn suitable for text classification? 

### ISSUE THREAD

**Issue by zm714981790** [locuslab/TCN#27]
I have a dataset and the text length is very small, and it's a multi-label task with 100+ class, most text length is 2,3,4, and i try to use tcn, but the result is not good(bag than pure cnn), my level is 9, and kernel is 2. Can you give me some suggest？

**Comment by shreydesai** [comment]
It may be useful to extract n-gram features from the text first. Traditional convolutional networks are well suited for this task – see [Kim's paper](https://arxiv.org/abs/1408.5882) on this. Many models will usually extract features using a convolutional network, then use a LSTM/GRU to learn sequential dependencies among the features. TCNs can be thought of as a drop-in replacement for the recurrent networks.
