### ISSUE TITLE
Any suggestion to use TCN for more than 1000 classes?

### ISSUE THREAD

**Issue by mchancan** [locuslab/TCN#29]
Paper default models and parameters doesn't perform well when trying to classify sequences with thousands of classes.

**Comment by jerrybai1995** [comment]
You probably shouldn't expect the model to work well on all tasks with just the default parameters. I would suggest some tuning on the number of layers and the dilation scheme. Maybe the optimizer and the dropout rates as well. 

BTW, the language modeling task itself is a sequence task with thousands (or actually, tens of thousands) of classes, so it also depends on the specific application that you are using TCN for.

**Comment by mchancan** [comment]
Yes, indeed, my application has only 1 sample image (32x64x1) per class. Maybe increasing the number of layers help but I'll try to find the best balance with the dilatation scheme and dropout as well. Thanks for your feedback.
