### ISSUE TITLE
Do TCN stride over time or over sequence length ?

### ISSUE THREAD

**Issue by mhashas** [locuslab/TCN#35]
So, you guys stated that tcn can be used as a dropped in replacement for lstm.

Lets assume I have a batch of images of shape: N x T x C x H x W. 
I reshape the images to be of size N X T X (-1). This is the x given to the forward function of the TCN. TCN is initialized with number of inputs T and the number of channels is [T] * num_levels_tcn. This means that effectively the TCN slides over (C x H x W) , or am I misunderstanding something ? I was under the impression (from the images in the paper) that TCN would slide over time.

**Comment by jerrybai1995** [comment]
You should convert the input to have dimension N x (-1) x T, where the features at each time step is at dim=1. So the TCN slides over T, not (C x H x W). Hope this helps!
