### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fengyuxie** [locuslab/TCN#37]
Hi,
I am a student. When I run your code, I have a question to think about. Your MNIST pixel task is very good. The data set is very formal. When I have a self-data set, what changes should I make on your basis and how to do them?
Best Regards

**Comment by fengyuxie** [comment]
there is a error :CUDA out of memory. Tried to allocate 230.00 MiB (GPU 0; 6.00 GiB total capacity; 4.17 GiB already allocated; 158.63 MiB free; 16.12 MiB cached).   but the batch_size=16 or 8 the error still happen 
I changed the input_channel=1 seq_length = int(50176/ input_channels) 50176=224*224  n_classes = 22

**Comment by jerrybai1995** [comment]
Hi @fengyuxie, it's hard to tell what the problem is. From the error you reported, your GPU only has 6GB of memory available. What machine/setting are you running on (how many GPUs, etc.)?

You could also use the NVIDIA APEX's half precision to resolve the memory issue, if needed.

**Comment by fengyuxie** [comment]
thanks for your suggestion,I will try to check out that again
