### ISSUE TITLE
scaling TCN to multiple GPUs

### ISSUE THREAD

**Issue by gupta-abhay** [locuslab/TCN#38]
i am currently training a model that requires a very large number of levels (effective history to be looked at) and i cannot fit it onto 1 GPU ... how can we parallelize TCNs to scale across multiple GPUs to fit one single model?

**Comment by jerrybai1995** [comment]
Hi! You can use `nn.DataParallel` to distribute a batch onto different GPUs. Simply use `model = nn.DataParallel(model)` after model initialization.
