### ISSUE TITLE
Any preprocessing required for the model?

### ISSUE THREAD

**Issue by deancorleone00** [locuslab/TCN#43]
I used zero padding to make records in my batch share the same length. Is there any other preprocessing required in order to use the model? (scaling, etc.)

**Comment by jerrybai1995** [comment]
There shouldn't be any on the model side. Depending on the data, you may want to normalize and scale the data **before** passing them into the TCN model.

**Comment by deancorleone00** [comment]
Thanks! Do you mean linearly scale (min-max normalize) or standardize (z-score normalize)? Or I should try both?

**Comment by jerrybai1995** [comment]
No harm to try both, but I would go with the latter first.
