### ISSUE TITLE
Using TCN as an Encoder 

### ISSUE THREAD

**Issue by jlim13** [locuslab/TCN#46]
How can we use the TCN as an encoder? How can we use the network to produce a single vector representation of the input like the context vector for RNNs? Do we take the last timestep of the output like here? 
https://github.com/locuslab/TCN/blob/2221de3323032faef7bde744b0e211bd274cb2d0/TCN/mnist_pixel/model.py#L15

**Comment by jerrybai1995** [comment]
Yup, I'd say that's a natural way of doing this.

**Comment by jlim13** [comment]
cool. thanks for the prompt response!
