### ISSUE TITLE
Question: layer sizes and time-series classification

### ISSUE THREAD

**Issue by danielhomola** [locuslab/TCN#47]
**Q1**
I noticed that in all examples you use the same hidden layer size across your layers. I was wondering if you've tried altering this and instead use a more tradition V shape, where earlier layers have more filters, gradually mapping down to fewer and fewer in deeper layers.

**Q2**
In the adding problem you use the very last element of the linear layer following the TCN to obtain a single scalar  output.
```python
self.linear1 = nn.Linear(num_channels[-1], output_size)
y1 = tcn(x)
out = F.relu(self.linear1(y1[:, :, -1]))
```
I was wondering if it would make sense to instead learn a combination across all time steps like so:
```python
self.linear1 = nn.Linear(num_channels[-1], output_size)
self.linear2 = nn.Linear(seq_len, 1)
y1 = tcn(x)
y2 = F.relu(self.linear1(y1.transpose(1, 2)))
y3 = self.linear2(y2.transpose(1, 2))[:, :, 0]
```

Here, we combine all filters from the last layer with a linear layer just like you did, but also combine across all time-steps.. Is there any  reason for not doing so?

Thanks a lot!

**Comment by jerrybai1995** [comment]
1) No, I didn't try it, but you could definitely give it a shot :-)

2) Taking the last time step is just a special case of your "combine + linear layer" design (in particular, where only the last few columns of the linear layer's weight are non-zero when applying Wx+b). I didn't do it just for the sake of simplicity, but there's no specific reason.
