### ISSUE TITLE
Shorter than seq_len sequences, padding from left?

### ISSUE THREAD

**Issue by danielhomola** [locuslab/TCN#48]
Sorry, silly question.. 

Let's say my seq_len is 100 and these are time-ordered, so `t0 < t1 < ... < t100` and I have a few instances in my batch which are shorter. So I'll pad them with zeros naturally from the left, i.e:
`batch_size=2`
- `0, 0, 0, t1 < t2 < ... < t97`
- `0, 0, 0, 0, t1 < t2 < ... < t96 `

Am I right in assuming that TCN will read (enforce causality) from left to right, i.e. the future time points have to be always to the right of the older ones? 

Thanks in advance..

**Comment by jerrybai1995** [comment]
Yep, that's the right way to do it.
