### ISSUE TITLE
Repo does not have a license

### ISSUE THREAD

**Issue by kdavis-mozilla** [locuslab/TCN#5]
To encourage exploration of TCN networks, this code needs a license, for example [Mozilla Public License 2.0](https://en.wikipedia.org/wiki/Mozilla_Public_License), that allows commercial and non-commercial entities to build upon this work.

Without such an explicit license, this code can not be used and built upon by other entities without exposing them to legal risk.

**Comment by jerrybai1995** [comment]
Hi, thanks for pointing this out. We just added an MIT license to this repo :-)
