### ISSUE TITLE
need clarification about paper and implementation

### ISSUE THREAD

**Issue by HilmiiKumdakci** [locuslab/TCN#53]
Hi,

As it is written in the paper, input and output should be the same length and output at time t depends on previous values of input. When I look at the implementation of adding problem, I see that input is 2*T where T is 200,300,400 etc. However output is just a scalar. What is the explanation for this ?

**Comment by jerrybai1995** [comment]
Hi,

The input is represented as a Tx2 tensor; in the output layer (which has length T), we only take the last time step to produce a scalar.

**Comment by HilmiiKumdakci** [comment]
Thanks for your explanation.

What I do not understand is, number of classes is 1, does not that mean length is equal to 1 ? If not so, where do you take last time step to produce scalar value of adding problem?

**Comment by jerrybai1995** [comment]
The number of classes is one means the width (the # of channels is 1), and the length is 1. But a TCN outputs a tensor with the same length as the input. There we only take the last time step of this full-length output, using `x[:,:,-1]`.
