### ISSUE TITLE
Is too large of receptive field wasteful?

### ISSUE THREAD

**Issue by johnsyin** [locuslab/TCN#55]
In my data, the sequence are all <10k length. The problem now is that I want to stack many layers, this means I will have very large receptive field even though alot of them are just padded values. 

I am wondering if I should stack TCN after one TCN (so the receptive field is smaller), instead of using one TCN with a long channel_size (many levels).

**Comment by jerrybai1995** [comment]
Hi @johnsyin,

Thank you for your question. Yes, if you don't want a large receptive field, you can dynamically set the dilation factor (so not necessarily 1,2,4,8,16,...; you can do 1,1,1,2,2,2,3,3,3,4,4,4,...). You can also simply stack multiple TCNs as you suggested.

**Comment by johnsyin** [comment]
I see, that might be a good way too.
