### ISSUE TITLE
On the meaning of validseqlen and seq_len

### ISSUE THREAD

**Issue by francescofolino** [locuslab/TCN#58]
First of all, thanks for sharing your code. I'm trying to understand your code in order to adapt it to my task. Surely, I'm missing something, then sorry in advance if this could appear a stupid question to you. Can I ask why, in the language model, you set the value of "seq_len" two times the value of "validseqlen"? Is there any reason behind it? Since, clearly, I did not well understand this part, can you please explain me the exact role of these two parameters? Thank you so much.

**Comment by jerrybai1995** [comment]
Hope this helps: https://github.com/locuslab/TCN/tree/master/TCN/word_cnn#note

**Comment by francescofolino** [comment]
> Hope this helps: https://github.com/locuslab/TCN/tree/master/TCN/word_cnn#note

Ok. Thank you!
