### ISSUE TITLE
LSTM and RNN used and issues of compatibility 

### ISSUE THREAD

**Issue by omermaymon** [locuslab/TCN#61]
hello!
I would like to know if the basic RNN and LSTM networks used by you in the article were the simple nn.LSTM and nn.RNN?
furthermore can you clarify on how to make pmnist_test, copymem_test and music_test compatible with those networks.

kind regards.
omer.

**Comment by jerrybai1995** [comment]
Hi @omermaymon ,

Yes, we used canonical LSTM and RNN from PyTorch.

You should simply replace the TCN with LSTM in the code. Just make sure you pass inputs of shape `(seq_len x bsz x C)` (which LSTM/RNN requires) instead of `(bsz x C x seq_len)` (which TCN uses).
