### ISSUE TITLE
issue about  Input of TCN

### ISSUE THREAD

**Issue by moelmadoka** [locuslab/TCN#62]
Hi,I would like to understand the meaning of the input (B, C, L) of the TCN model. B represents the batch size. Does C represent the dimension of each sample feature? Does L represent the sequence length of each sample? Does args.nhid in the network represent the convolution of the length of the sample sequence? For multivariate time series modeling, what input should tcn handle? For example, data.shape is (data_number, feature_dim).

**Comment by jerrybai1995** [comment]
Your interpretation of C and L is correct.

For multivariate time series modeling, you should use it similar to how you use RNN/LSTM. Make sure your data has a temporal/sequence-length dimension.
