### ISSUE TITLE
ModuleNotFoundError: No module named 'tcn'

### ISSUE THREAD

**Issue by fjehlik** [locuslab/TCN#63]
Howdy Folks,

Per the instructions, I installed via "pip install keras-tcn". My system is Linux (Ubuntu 20.04) and I use Anaconda 2.0.3 as my package manager, Spyder 4.2.5 as my python editor (Python 3.8). I verified that the tcn module had been added to the Anaconda site packages (it is in the 'tcn' folder located here):

 .~/anaconda3/lib/python3.8/site-packages/tcn

However, when I open an instance of Spyder and try importing using the following: 

from tcn import TCN, tcn_full_summary 

I receive the No module named 'tcn' error. Any ideas on solving this will be appreciated!

**Comment by jerrybai1995** [comment]
Hi, 

Did you mean to use [keras-tcn](https://github.com/philipperemy/keras-tcn) or TCN (this repo)?

**Comment by fjehlik** [comment]
My bad, I had a couple of windows open and posted to the wrong repo. Apolgoies, I meant to post to keras-tcn repo.
