### ISSUE TITLE
Causality 

### ISSUE THREAD

**Issue by amirkargar** [locuslab/TCN#8]
Hi,
In which part of the code you make sure the network is causal? Is it the `Chomp1d` ?

Thanks a lot!
Amir

**Comment by Songweiping** [comment]
Hi @jerrybai1995 ,
Could you explain more on the causality? How do padding and chomp1d work? 

Many thanks!

**Comment by jerrybai1995** [comment]
Please see Figure 1(a) in our paper for reference. We pad by (k-1)*d on the two sides of the input for convolution, and then use Chomp1d to remove the (k-1)*d output elements on the right. 

If you draw a figure yourself, you would find that this is equivalent to removing the "future elements", which ensures causality.

**Comment by Songweiping** [comment]
Thanks for the prompt reply.

Do you mean you pad by (k-1)*d zeros on both sides of input? It seems only on left side in Figure 1(a). Besides, padding on left side makes sense to me. I must misunderstand something.

Will there be some leakage if we only pad on left side without Chomp1d? Based on my current understanding, if we only pad (k-1)*d elements on left side, convolutional layer will produce a sequence with the same length of input. Is there something wrong?

Thanks!

**Comment by jerrybai1995** [comment]
Padding on the left only is equivalent to what we are doing here. So you can also implement it as
```python
x = F.pad(x, ((k-1)*d, 0))
out = self.conv(x)
```

**Comment by Songweiping** [comment]
Thank you so much!

**Comment by kwanUm** [comment]
Sorry for the late timing of asking this: I understand the intuition of  using padding + `Chomp1D` to create a causal conv.
Nevertheless, isn't the use of these make the model doubly dependent on "past context"? Meaning, in order to calculate t samples, the model needs to be given t + h samples (where h number of samples "from the past" before the 't' samples given)?
The use of padding + `Chomp1D` increases the "past context by a factor of 2 IIUC.

**Comment by StatMixedML** [comment]
@jerrybai1995 Thanks for clarifying the use of the causality!

However, I dont't understand the residual connection step

https://github.com/locuslab/TCN/blob/master/TCN/tcn.py#L45

If `res = x`, should't the `x` also be causal in the sense of removing the future values, i.e., something like `out+res[:,:,-out.shape[2]:]`
