### ISSUE TITLE
figure 4 (b) of paper

### ISSUE THREAD

**Issue by kashif** [locuslab/TCN#9]
is the figure 4 (b) of the paper for T=1000 or T=2000? If its for T=1000 then shouldn't the random guess baseline loss be 0.02?

**Comment by jerrybai1995** [comment]
Yes, you are right, that is the plot for T=2000. We will correct this in an updated version.

Here is the plot for T=1000, in case you are curious:
<img width="756" alt="copy1000" src="https://user-images.githubusercontent.com/11433746/38456869-29e2047e-3a57-11e8-9e68-9b4f4a43968f.png">
